/* PROJEÇÂO - O QUE IRÁ APARECER NA TELA */

SELECT nomeColunas;

/* ORIGEM - DE ONDE VIRÁ ESTES DADOS */

FROM nomeTabela;

/* JOIN - A JUNÇÃO DE 2 OU MAIS TABELAS */

INNER JOIN nomeTabela2
ON chaveTabela1 = chaveTabela2;

/* SELEÇÃO WHERE - A FILTRAGEM DOS DADOS EXEMPLO O SEXO */

WHERE coluna = dado;

/* EXEMPLO: PROJEÇÃO - ORIGEM - JUNÇÃO - SELEÇÃO */

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
	INNER JOIN ENDERECO /* JUNÇÃO */
	ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /* SELEÇÃO */
