/* Relacionamentos */

/* Estrutura 2 tabelas */

SELECT colunaTab1, colunaTab2
FROM tabela1
INNER JOIN tabela2
ON chaveTab1 = chaveTab2;

SELECT colunaTab1, colunaTab2
FROM tabela1
RIGHT JOIN tabela2
ON chaveTab1 = chaveTab2;

SELECT colunaTab1, colunaTab2
FROM tabela1
LEFT JOIN tabela2
ON chaveTab1 = chaveTab2;

/* Exemplo */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
RIGHT JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
LEFT JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

/* Estrutura 3 ou mais tabelas - Utiliza o identificador para cada tabela */

SELECT TAB1.colunaTab1, TAB2.colunaTab2, TAB3.colunaTab3
FROM tabela1 TAB1
INNER JOIN tabela2 TAB2
ON TAB1.chaveTab1 = TAB2.chaveTab2;
INNER JOIN tabela3 TAB3
ON TAB1.chaveTab1 = TAB2.chaveTab3;

SELECT TAB1.colunaTab1, TAB2.colunaTab2, TAB3.colunaTab3
FROM tabela1 TAB1
RIGHT JOIN tabela2 TAB2
ON TAB1.chaveTab1 = TAB2.chaveTab2;
RIGHT JOIN tabela3 TAB3
ON TAB1.chaveTab1 = TAB2.chaveTab3;

SELECT TAB1.colunaTab1, TAB2.colunaTab2, TAB3.colunaTab3
FROM tabela1 TAB1
LEFT JOIN tabela2 TAB2
ON TAB1.chaveTab1 = TAB2.chaveTab2;
LEFT JOIN tabela3 TAB3
ON TAB1.chaveTab1 = TAB2.chaveTab3;

/* Exemplo */

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.NUMERO, T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.NUMERO, T.TIPO
FROM CLIENTE C
RIGHT JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
RIGHT JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.NUMERO, T.TIPO
FROM CLIENTE C
LEFT JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;
