/* Subquery */

/* Estrutura */

SELECT colunas
FROM tabela
WHERE coluna =/</> (SELECT coluna FROM tabela);

/* Exemplo */

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO < (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/* OPERAÇÕES EM LINHA */

SELECT NOME, 
			 JANEIRO, 
			 FEVEREIRO, 
			 MARCO, 
			 (JANEIRO+FEVEREIRO+MARCO) AS "TOTAL", 
			 TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3, 2) AS "MEDIA"
FROM VENDEDORES;
