/* Estrutura de uma Trigger */

/* Alterando o delimitador */

DELIMITER $

/* Criando a Trigger */

CREATE TRIGGER NOME
	BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
	FOR EACH ROW /*PARA CADA LINHA*/
BEGIN /*INICIO*/
	/*QUALQUER COMANDO SQL*/
END /*FIM*/
$

/* Retornando o delimitador para o original */

DELIMITER ;

/* Exemplo 1 */

DELIMITER $

CREATE TRIGGER BACKUP_USER
	BEFORE DELETE ON USUARIO
	FOR EACH ROW /*PARA CADA LINHA*/
BEGIN
	INSERT INTO BKP_USER VALUES(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END
$

DELIMITER ;

/* Exemplo 2 */

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);
END
$

/* Exemplo 3 */

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR, 'I');
END
$

DELIMITER ;

/* EXEMPLO TRIGGER DE AUDITORIA */

CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);
  
DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');
END
$

DELIMITER ;
